In [4]:
import pandas as pd

In [9]:
nums = [9,4,1,7,5,8,23,56,98,12,7,8,9,9]
nums = sorted(nums)
k = 3
for i in range(len(nums)-k+1):
    lst = nums[i:i+k]
    print(lst,lst[0],lst[-1],lst[-1]-lst[0])

[1, 4, 5] 1 5 4
[4, 5, 7] 4 7 3
[5, 7, 7] 5 7 2
[7, 7, 8] 7 8 1
[7, 8, 8] 7 8 1
[8, 8, 9] 8 9 1
[8, 9, 9] 8 9 1
[9, 9, 9] 9 9 0
[9, 9, 12] 9 12 3
[9, 12, 23] 9 23 14
[12, 23, 56] 12 56 44
[23, 56, 98] 23 98 75

In [22]:
student_data = [
    [1,15],
    [2,11],
    [3,11],
    [4,20]
]
df = pd.DataFrame(student_data,columns=['id','score'])
df

   id  score
0   1     15
1   2     11
2   3     11
3   4     20

In [10]:
list(df.shape)

[4, 2]

In [11]:
df.iloc[0:2,:]

   id  score
0   1     15
1   2     11

In [13]:
df.assign(bonus=df['score']*2)

   id  score  bonus
0   1     15     30
1   2     11     22
2   3     11     22
3   4     20     40

In [18]:
df.drop_duplicates(subset=['score'],keep=False)

   id  score
0   1     15
3   4     20

In [24]:
df.rename(columns={'score':'grade'},inplace=False)

   id  grade
0   1     15
1   2     11
2   3     11
3   4     20

In [31]:
pd.concat([df,pd.DataFrame({'id':[5,6],'score':[10,12]})],ignore_index=True)

   id  score
0   1     15
1   2     11
2   3     11
3   4     20
4   5     10
5   6     12

In [33]:
weather = pd.DataFrame({
    'city': ['JacksonVile']*5 + ['ElPaso']*5,
    'month': ['January', 'February', 'March', 'April', 'May','January', 'February', 'March', 'April', 'May'],
    'temperature': [70, 75, 80, 85, 90, 65, 70, 75, 80, 85]
})
weather

          city     month  temperature
0  JacksonVile   January           70
1  JacksonVile  February           75
2  JacksonVile     March           80
3  JacksonVile     April           85
4  JacksonVile       May           90
5       ElPaso   January           65
6       ElPaso  February           70
7       ElPaso     March           75
8       ElPaso     April           80
9       ElPaso       May           85

In [36]:
weather_pivot = weather.pivot(index='month',columns='city',values='temperature')
weather_pivot

city      ElPaso  JacksonVile
month
April         80           85
February      70           75
January       65           70
March         75           80
May           85           90

In [41]:
report = pd.DataFrame({
    'product': ['umbrella','sleeping_bag'],
    'quarter_1': [417,800],
    'quarter_2': [224,936],
    'quarter_3': [379,93],
    'quarter_4': [611,875]
})
report

        product  quarter_1  quarter_2  quarter_3  quarter_4
0      umbrella        417        224        379        611
1  sleeping_bag        800        936         93        875

In [43]:
report.melt(id_vars='product',var_name='quarter',value_name='sales').sort_values(by='sales',ascending=False)['product']

3    sleeping_bag
7    sleeping_bag
1    sleeping_bag
6        umbrella
0        umbrella
4        umbrella
2        umbrella
5    sleeping_bag
Name: product, dtype: object